name: weather-app

services:

  database:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: weather-viewer
    build:
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '8080:8080'
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - HIKARI_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - HIKARI_DATASOURCE_CONNECTIONURL=jdbc:postgresql://database:5432/postgres
      - WEATHER_API_KEY=${WEATHER_API_KEY}


volumes:
  postgres-data:


networks:
  app-network:
    driver: bridge