hikari.datasource.driver=org.postgresql.Driver
hikari.datasource.connectionUrl=jdbc:postgresql://localhost:5432/new
hikari.datasource.username=postgres
hikari.datasource.password=123
hikari.datasource.min_pool_size=5
hikari.datasource.max_pool_size=5
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.format_sql=true
hibernate.hbm2ddl.auto=none
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
session_duration_sec=1800